### ISSUE TITLE
PhishDetect node -> MISP instance

### ISSUE THREAD

**Issue by mfc** [phishdetect/phishdetect-utils#1]
based on https://github.com/phishdetect/phishdetect-node/issues/5#issuecomment-562894822 this ticket is for a middleware Python script that takes care of communicating with the two separate API servers (PhishDetect node + MISP instance)

**Comment by mfc** [comment]
@liliakai i think [this](https://github.com/phishdetect/phishdetect-utils/blob/8a96f69a94ab54cff0eeb0962b4262cd43378ff5/misp.py#L104) should be "MISP instance", I think variables should maybe be tweaked to reflect. does https://mispbeta.circl.lu need API token? in which case maybe it's not useful to have as default.

**Comment by liliakai** [comment]
Good catch, will fix. AFAIK all MISP instances need an API token.

**Comment by liliakai** [comment]
I guess I'll change it to default to an environment variable, for consistency with the other arguments.
